### ISSUE TITLE
Problem with layout

### ISSUE THREAD

**Issue by ozee31** [WyriHaximus/TwigView#16]
Hi,

I have a problem with Layout

If use default.ctp with a twig view it's works but if i use a default layout with twig don't work (don't show de view, just show layout)

## First test
```HTML
<!-- layout.tpl -->
<h1>Hi</h1>

<!-- page.tpl -->
<p>Test</p>
```
Show just "Hi"

## Second test
```HTML
<!-- layout.tpl -->
<h1>Hi</h1>
{% block content %}{% endblock %}

<!-- page.tpl -->
<p>yo</p>
{% block content %}<p>test</p>{% endblock %}
```
Show just "Hi"

### Other test
```HTML
<!-- layout.tpl -->
<h1>Hi</h1>
{% block content %}{% endblock %}

<!-- page.tpl -->
{% extends 'Layout/default' %}

{% block content %}<p>test</p>{% endblock %}
```
Show just "Hi"  

Thank you for your help

**Comment by WyriHaximus** [comment]
Normally that would work, but due to the nature how cake handles it views and layouts seperately. It first renders the view and then places the result into the layout when rendering it. There are two ways of handling this:

# A
In you layout `.tpl` place the following line to get the result from your view:

```twig
{{ _view.fetch('content')|raw }}
```

# B

Make sure your `Layout/default.tpl` only consits of:

```twig
{{ _view.fetch('content')|raw }}
```
Adjusting your second example a little bit, take note of the filenames:

```twig
<!-- ozee31.tpl -->
<h1>Hi</h1>
{% block content %}{% endblock %}

<!-- page.tpl -->
{% extends 'Layout/ozee31' %}

{% block content %}<p>test</p>{% endblock %}
```

**Comment by ozee31** [comment]
Thank you, it's work

**Comment by WyriHaximus** [comment]
Awesome :+1:
